### ISSUE TITLE
Use Git tags (and GitHub releases)

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [freudFlintstone/polymer-nfc#1]
@freudFlintstone Please add Git tags. I want to publish this web component on https://webcomponents.org. But this repo must have a tagged release before it can be published.

**Comment by freudFlintstone** [comment]
Thanks @FluorescentHallucinogen, just added a 1.0 version for release! But webcomponents.org still says there are no tagged releases. Any idea why that wouldn't work?

**Comment by FluorescentHallucinogen** [comment]
Use `1.0.0` instead of `1.0`. See https://semver.org for more info. :wink:

**Comment by freudFlintstone** [comment]
Thanks, it's published!
